export const TEAM_NAME_OPTIONS = [
  "阿根廷",
  "澳大利亚",
  "比利时",
  "波黑",
  "巴西",
  "佛得角",
  "喀麦隆",
  "加拿大",
  "南非",
  "奥地利",
  "阿尔及利亚",
  "智利",
  "中国",
  "捷克",
  "哥伦比亚",
  "哥斯达黎加",
  "科特迪瓦",
  "克罗地亚",
  "库拉索",
  "丹麦",
  "厄瓜多尔",
  "埃及",
  "英格兰",
  "法国",
  "德国",
  "刚果民主共和国",
  "加纳",
  "海地",
  "洪都拉斯",
  "伊拉克",
  "伊朗",
  "意大利",
  "牙买加",
  "日本",
  "约旦",
  "韩国",
  "墨西哥",
  "摩洛哥",
  "荷兰",
  "新西兰",
  "尼日利亚",
  "挪威",
  "巴拿马",
  "巴拉圭",
  "秘鲁",
  "波兰",
  "葡萄牙",
  "卡塔尔",
  "沙特阿拉伯",
  "苏格兰",
  "塞内加尔",
  "塞尔维亚",
  "西班牙",
  "瑞典",
  "瑞士",
  "突尼斯",
  "土耳其",
  "乌克兰",
  "乌兹别克斯坦",
  "乌拉圭",
  "美国",
  "威尔士",
];

const TEAM_NAME_ALIASES: Record<string, string> = {
  arg: "阿根廷",
  argentina: "阿根廷",
  aus: "澳大利亚",
  australia: "澳大利亚",
  bel: "比利时",
  belgium: "比利时",
  bih: "波黑",
  "bosnia & herzegovina": "波黑",
  "bosnia and herzegovina": "波黑",
  bra: "巴西",
  brazil: "巴西",
  cpv: "佛得角",
  "cape verde": "佛得角",
  cam: "喀麦隆",
  cameroon: "喀麦隆",
  can: "加拿大",
  canada: "加拿大",
  rsa: "南非",
  "south africa": "南非",
  aut: "奥地利",
  austria: "奥地利",
  alg: "阿尔及利亚",
  algeria: "阿尔及利亚",
  chi: "智利",
  chile: "智利",
  chn: "中国",
  china: "中国",
  cze: "捷克",
  czechia: "捷克",
  "czech republic": "捷克",
  col: "哥伦比亚",
  colombia: "哥伦比亚",
  crc: "哥斯达黎加",
  "costa rica": "哥斯达黎加",
  civ: "科特迪瓦",
  "cote d'ivoire": "科特迪瓦",
  "côte d'ivoire": "科特迪瓦",
  "ivory coast": "科特迪瓦",
  象牙海岸: "科特迪瓦",
  cro: "克罗地亚",
  croatia: "克罗地亚",
  cuw: "库拉索",
  curacao: "库拉索",
  "curaçao": "库拉索",
  den: "丹麦",
  denmark: "丹麦",
  ecu: "厄瓜多尔",
  ecuador: "厄瓜多尔",
  egy: "埃及",
  egypt: "埃及",
  eng: "英格兰",
  england: "英格兰",
  fra: "法国",
  france: "法国",
  ger: "德国",
  germany: "德国",
  cod: "刚果民主共和国",
  "dr congo": "刚果民主共和国",
  "democratic republic of the congo": "刚果民主共和国",
  gha: "加纳",
  ghana: "加纳",
  hai: "海地",
  haiti: "海地",
  hon: "洪都拉斯",
  honduras: "洪都拉斯",
  irq: "伊拉克",
  iraq: "伊拉克",
  irn: "伊朗",
  iran: "伊朗",
  ita: "意大利",
  italy: "意大利",
  jam: "牙买加",
  jamaica: "牙买加",
  jpn: "日本",
  japan: "日本",
  jor: "约旦",
  jordan: "约旦",
  kor: "韩国",
  "korea republic": "韩国",
  "south korea": "韩国",
  mex: "墨西哥",
  mexico: "墨西哥",
  mar: "摩洛哥",
  morocco: "摩洛哥",
  ned: "荷兰",
  netherlands: "荷兰",
  nzl: "新西兰",
  "new zealand": "新西兰",
  纽西兰: "新西兰",
  nga: "尼日利亚",
  nigeria: "尼日利亚",
  nor: "挪威",
  norway: "挪威",
  pan: "巴拿马",
  panama: "巴拿马",
  par: "巴拉圭",
  paraguay: "巴拉圭",
  per: "秘鲁",
  peru: "秘鲁",
  pol: "波兰",
  poland: "波兰",
  por: "葡萄牙",
  portugal: "葡萄牙",
  qat: "卡塔尔",
  qatar: "卡塔尔",
  ksa: "沙特阿拉伯",
  "saudi arabia": "沙特阿拉伯",
  沙地阿拉伯: "沙特阿拉伯",
  sco: "苏格兰",
  scotland: "苏格兰",
  sen: "塞内加尔",
  senegal: "塞内加尔",
  srb: "塞尔维亚",
  serbia: "塞尔维亚",
  esp: "西班牙",
  spain: "西班牙",
  swe: "瑞典",
  sweden: "瑞典",
  sui: "瑞士",
  switzerland: "瑞士",
  tun: "突尼斯",
  tunisia: "突尼斯",
  突尼西亚: "突尼斯",
  tur: "土耳其",
  turkey: "土耳其",
  ukr: "乌克兰",
  ukraine: "乌克兰",
  uzb: "乌兹别克斯坦",
  uzbekistan: "乌兹别克斯坦",
  uru: "乌拉圭",
  uruguay: "乌拉圭",
  usa: "美国",
  "united states": "美国",
  "united states of america": "美国",
  wales: "威尔士",
};

const TEAM_FLAGS: Record<string, string> = {
  阿根廷: "🇦🇷",
  澳大利亚: "🇦🇺",
  比利时: "🇧🇪",
  波黑: "🇧🇦",
  巴西: "🇧🇷",
  佛得角: "🇨🇻",
  喀麦隆: "🇨🇲",
  加拿大: "🇨🇦",
  南非: "🇿🇦",
  奥地利: "🇦🇹",
  阿尔及利亚: "🇩🇿",
  智利: "🇨🇱",
  中国: "🇨🇳",
  捷克: "🇨🇿",
  哥伦比亚: "🇨🇴",
  哥斯达黎加: "🇨🇷",
  科特迪瓦: "🇨🇮",
  克罗地亚: "🇭🇷",
  库拉索: "🇨🇼",
  丹麦: "🇩🇰",
  厄瓜多尔: "🇪🇨",
  埃及: "🇪🇬",
  英格兰: "\u{1F3F4}\u{E0067}\u{E0062}\u{E0065}\u{E006E}\u{E0067}\u{E007F}",
  法国: "🇫🇷",
  德国: "🇩🇪",
  刚果民主共和国: "🇨🇩",
  加纳: "🇬🇭",
  海地: "🇭🇹",
  洪都拉斯: "🇭🇳",
  伊拉克: "🇮🇶",
  伊朗: "🇮🇷",
  意大利: "🇮🇹",
  牙买加: "🇯🇲",
  日本: "🇯🇵",
  约旦: "🇯🇴",
  韩国: "🇰🇷",
  墨西哥: "🇲🇽",
  摩洛哥: "🇲🇦",
  荷兰: "🇳🇱",
  新西兰: "🇳🇿",
  尼日利亚: "🇳🇬",
  挪威: "🇳🇴",
  巴拿马: "🇵🇦",
  巴拉圭: "🇵🇾",
  秘鲁: "🇵🇪",
  波兰: "🇵🇱",
  葡萄牙: "🇵🇹",
  卡塔尔: "🇶🇦",
  沙特阿拉伯: "🇸🇦",
  苏格兰: "\u{1F3F4}\u{E0067}\u{E0062}\u{E0073}\u{E0063}\u{E0074}\u{E007F}",
  塞内加尔: "🇸🇳",
  塞尔维亚: "🇷🇸",
  西班牙: "🇪🇸",
  瑞典: "🇸🇪",
  瑞士: "🇨🇭",
  突尼斯: "🇹🇳",
  土耳其: "🇹🇷",
  乌克兰: "🇺🇦",
  乌兹别克斯坦: "🇺🇿",
  乌拉圭: "🇺🇾",
  美国: "🇺🇸",
  威尔士: "\u{1F3F4}\u{E0067}\u{E0062}\u{E0077}\u{E006C}\u{E0073}\u{E007F}",
};

export function formatTeamName(name: string): string {
  const trimmed = name.trim();
  const lower = trimmed.toLowerCase();
  const exact = TEAM_NAME_ALIASES[lower];

  if (exact) {
    return exact;
  }

  for (const [alias, chineseName] of Object.entries(TEAM_NAME_ALIASES)) {
    if (lower.startsWith(`${alias} `)) {
      return `${chineseName}${trimmed.slice(alias.length)}`;
    }
  }

  return trimmed;
}

export function formatMatchTitle(homeTeam: string, awayTeam: string): string {
  return `${formatTeamName(homeTeam)} vs ${formatTeamName(awayTeam)}`;
}

export function getTeamFlag(name: string): string {
  return TEAM_FLAGS[formatTeamName(name)] ?? "🏳";
}
