export const TEAM_NAME_OPTIONS = [
  "阿根廷",
  "澳大利亚",
  "比利时",
  "巴西",
  "喀麦隆",
  "加拿大",
  "智利",
  "中国",
  "哥伦比亚",
  "哥斯达黎加",
  "克罗地亚",
  "丹麦",
  "厄瓜多尔",
  "埃及",
  "英格兰",
  "法国",
  "德国",
  "加纳",
  "伊朗",
  "意大利",
  "日本",
  "韩国",
  "墨西哥",
  "摩洛哥",
  "荷兰",
  "新西兰",
  "尼日利亚",
  "挪威",
  "巴拉圭",
  "秘鲁",
  "波兰",
  "葡萄牙",
  "卡塔尔",
  "沙特阿拉伯",
  "苏格兰",
  "塞内加尔",
  "塞尔维亚",
  "西班牙",
  "瑞典",
  "瑞士",
  "突尼斯",
  "土耳其",
  "乌克兰",
  "乌拉圭",
  "美国",
  "威尔士",
];

const TEAM_NAME_ALIASES: Record<string, string> = {
  arg: "阿根廷",
  argentina: "阿根廷",
  aus: "澳大利亚",
  australia: "澳大利亚",
  bel: "比利时",
  belgium: "比利时",
  bra: "巴西",
  brazil: "巴西",
  cam: "喀麦隆",
  cameroon: "喀麦隆",
  can: "加拿大",
  canada: "加拿大",
  chi: "智利",
  chile: "智利",
  chn: "中国",
  china: "中国",
  col: "哥伦比亚",
  colombia: "哥伦比亚",
  crc: "哥斯达黎加",
  "costa rica": "哥斯达黎加",
  cro: "克罗地亚",
  croatia: "克罗地亚",
  den: "丹麦",
  denmark: "丹麦",
  ecu: "厄瓜多尔",
  ecuador: "厄瓜多尔",
  egy: "埃及",
  egypt: "埃及",
  eng: "英格兰",
  england: "英格兰",
  fra: "法国",
  france: "法国",
  ger: "德国",
  germany: "德国",
  gha: "加纳",
  ghana: "加纳",
  irn: "伊朗",
  iran: "伊朗",
  ita: "意大利",
  italy: "意大利",
  jpn: "日本",
  japan: "日本",
  kor: "韩国",
  "korea republic": "韩国",
  "south korea": "韩国",
  mex: "墨西哥",
  mexico: "墨西哥",
  mar: "摩洛哥",
  morocco: "摩洛哥",
  ned: "荷兰",
  netherlands: "荷兰",
  nzl: "新西兰",
  "new zealand": "新西兰",
  nga: "尼日利亚",
  nigeria: "尼日利亚",
  nor: "挪威",
  norway: "挪威",
  par: "巴拉圭",
  paraguay: "巴拉圭",
  per: "秘鲁",
  peru: "秘鲁",
  pol: "波兰",
  poland: "波兰",
  por: "葡萄牙",
  portugal: "葡萄牙",
  qat: "卡塔尔",
  qatar: "卡塔尔",
  ksa: "沙特阿拉伯",
  "saudi arabia": "沙特阿拉伯",
  sco: "苏格兰",
  scotland: "苏格兰",
  sen: "塞内加尔",
  senegal: "塞内加尔",
  srb: "塞尔维亚",
  serbia: "塞尔维亚",
  esp: "西班牙",
  spain: "西班牙",
  swe: "瑞典",
  sweden: "瑞典",
  sui: "瑞士",
  switzerland: "瑞士",
  tun: "突尼斯",
  tunisia: "突尼斯",
  tur: "土耳其",
  turkey: "土耳其",
  ukr: "乌克兰",
  ukraine: "乌克兰",
  uru: "乌拉圭",
  uruguay: "乌拉圭",
  usa: "美国",
  "united states": "美国",
  "united states of america": "美国",
  wales: "威尔士",
};

export function formatTeamName(name: string): string {
  const trimmed = name.trim();
  const lower = trimmed.toLowerCase();
  const exact = TEAM_NAME_ALIASES[lower];

  if (exact) {
    return exact;
  }

  for (const [alias, chineseName] of Object.entries(TEAM_NAME_ALIASES)) {
    if (lower.startsWith(`${alias} `)) {
      return `${chineseName}${trimmed.slice(alias.length)}`;
    }
  }

  return trimmed;
}

export function formatMatchTitle(homeTeam: string, awayTeam: string): string {
  return `${formatTeamName(homeTeam)} vs ${formatTeamName(awayTeam)}`;
}
